In [1]:
import numpy as np

#### Create an array of 10 zeros

In [3]:
zero_matrix = np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create a function that will iterate through the list and will tell what each item is

In [4]:
for item_seeker in matrix_ofChoice(x):
    return x

SyntaxError: 'return' outside function (<ipython-input-4-1a1717226068>, line 2)

#### Create an array of 10 ones

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [6]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of intergers from 10 to 50

In [9]:
np.arange(10, 51) # or you can alternatively also type np.arange(10, 51, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### create an array of even integers from 10 to 50

In [10]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
#### Create 3x3 identity matrix

In [19]:
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# What are the differences in np.eye(3), np.eye(3,3) and np.eye(3,3,3) and Why???

#### Use NumPy to generate random numbers between 0 and 1, i) one number, ii) 25 numbers iii) 5x5 matrix of 25 numbers

In [20]:
np.random.rand(1)

array([0.86439864])

In [21]:
np.random.rand(25)

array([0.19941016, 0.67667273, 0.35659838, 0.31726253, 0.59665877,
       0.73768252, 0.04265345, 0.81960259, 0.42558498, 0.36869338,
       0.24195899, 0.5816904 , 0.59272697, 0.1757371 , 0.2305473 ,
       0.22148043, 0.14529226, 0.56654377, 0.31941915, 0.93668909,
       0.8740571 , 0.52244357, 0.75242277, 0.64533561, 0.87206364])

In [22]:
np.random.rand(5,5)

array([[0.64036728, 0.10388969, 0.24333068, 0.26524018, 0.9202659 ],
       [0.10334315, 0.12573962, 0.58758112, 0.45489292, 0.069867  ],
       [0.38623404, 0.17758696, 0.58470356, 0.57609017, 0.00575911],
       [0.86520058, 0.94662394, 0.89860726, 0.8393896 , 0.9896829 ],
       [0.260303  , 0.0222418 , 0.71239349, 0.38897171, 0.85641281]])

In [28]:
np.random.random(25).reshape(5,5)

array([[0.50789106, 0.33063349, 0.72809942, 0.1680776 , 0.66375457],
       [0.32824899, 0.64162001, 0.24041811, 0.82176152, 0.57481433],
       [0.8684015 , 0.02658588, 0.46022879, 0.01588187, 0.38790493],
       [0.31626525, 0.46920086, 0.35794538, 0.34171182, 0.58163745],
       [0.37788266, 0.41930552, 0.85022784, 0.40012033, 0.50065619]])

#### Look up more examples and methods for random selections